services:
  - type: web
    name: saas-starter-api
    runtime: node
    repo: https://github.com/ndumisoMenz/saas-starter.git
    branch: main
    rootDir: .
    buildCommand: npm install && npm run build --workspace=apps/api
    startCommand: npm run start --workspace=apps/api
    envVars:
      - key: NODE_ENV
        value: production

      - key: DATABASE_URL
        sync: false

      - key: DIRECT_URL
        sync: false

      - key: JWT_SECRET
        sync: false

      - key: AWS_ACCESS_KEY_ID
        sync: false

      - key: AWS_SECRET_ACCESS_KEY
        sync: false

      - key: AWS_REGION
        value: af-south-1

      - key: AWS_BUCKET_NAME
        sync: false